# Copyright (c) 2015 Intel Corporation. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

sudo: false

os:
  - linux

language: android

android:
  components:
    - tools-24.1.2
    - platform-tools-22
    - build-tools-22.0.0
    - android-22

env:
  - XWALK_CHANNEL=canary XWALK_VERSION=17.45.432.0

before_install:
  # Travis builder git clone REC into otcshare/realsense-extensions-crosswalk
  # and change directory into it.
  # Before install, we need to go back to the build root directory.
  - cd ../..

install:
  # Install depot_tools
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git `pwd`/src/third_party/depot_tools
  - export PATH="$PATH":`pwd`/src/third_party/depot_tools;
  # Download Crosswalk
  - curl -LO https://download.01.org/crosswalk/releases/crosswalk/android/${XWALK_CHANNEL}/${XWALK_VERSION}/crosswalk-${XWALK_VERSION}.zip && unzip crosswalk-${XWALK_VERSION}.zip && rm crosswalk-${XWALK_VERSION}.zip
  - chmod a+x `pwd`/crosswalk-${XWALK_VERSION}/make_apk.py
  - export PATH="$PATH":`pwd`/crosswalk-${XWALK_VERSION}
  # Copy REC repo from Travis' git.checkout step
  - cp -r otcshare/realsense-extensions-crosswalk src/extensions
  # Sync the project
  - echo "solutions=[{'name':'src','url':'git@github.com:otcshare/crosswalk-extensions-sdk.git@origin/master','deps_file':'DEPS','managed':False,'custom_deps':{'extensions/build/rssdk/android/intel_realsense_sdk':'git@github.com:otcshare/intel_realsense_sdk.git'},'safesync_url':'',},]" > .gclient
  - echo "hooks=[{'name':'prepare_android_tools','pattern':'.','action':['bash','src/third_party/android_tools/prepare_android_tools.sh'],},]" >> .gclient
  - echo "target_os=['android']" >> .gclient
  - echo "{'GYP_DEFINES':'OS=android target_arch=ia32',}" > chromium.gyp_env
  - gclient sync

script:
  - cd src
  - python gyp_all
  - ninja -C out/Release all

notifications:
  email:
    recipients:
      - ningxin.hu@intel.com
      - halton.huo@intel.com
    on_success: always
    on_failure: always
